run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - errcheck
    - typecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0